use stressFeatures
GO
Exec create_tables_storedProcedure
GO
EXEC create_ecg_storedProcedure
EXEC create_EEG_Delta_tables_storedProcedure
EXEC create_EEG_Theta_tables_storedProcedure
EXEC create_EEG_Alpha_tables_storedProcedure
EXEC create_EEG_Beta_1_tables_storedProcedure
EXEC create_EEG_Beta_2_tables_storedProcedure
EXEC create_EEG_Gamma_1_tables_storedProcedure
EXEC create_EEG_Gamma_2_tables_storedProcedure
EXEC create_EEG_Ratio_Alpha_tables_storedProcedure
EXEC create_EEG_Ratio_Beta_1_tables_storedProcedure
EXEC create_EEG_Ratio_Beta_2_tables_storedProcedure